version: '3.7'
services:
  forum:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - db
  db:
    image: postgres:9.4
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: dbdata
        target: "/var/lib/postgresql/data"
    environment:
     - POSTGRES_PASSWORD=password
  pgAdmin:
    image: dpage/pgadmin4
    ports:
      - "9000:80"
    volumes:
      - type: volume
        source: pgadmindata
        target: "/var/lib/pgadmin"
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@test.com
      - PGADMIN_DEFAULT_PASSWORD=test
volumes:
  dbdata:
  pgadmindata:


